In [2]:
import numpy as np

from cryosiam.transforms.array import RandomMaskedViews

In [30]:
patch = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]])

In [31]:
patch.shape

(1, 4, 4)

In [33]:
view_finder = RandomMaskedViews(patch.shape[1:], view_size=(2,2), overlap=0.5)

In [37]:
views = view_finder(patch)

In [38]:
views

{'view1': array([[[ 7,  8],
         [11, 12]]]),
 'view2': array([[[11, 12],
         [15, 16]]]),
 'mask1': tensor([[[1, 1],
          [1, 1]]]),
 'mask2': tensor([[[1, 1],
          [1, 1]]])}

In [39]:
print(patch)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]]
